### ISSUE TITLE
Discrepancies between SpatialStructure-BB and population values

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/Pregnancy-Models#15]
Example: Organism|Endometrium|Volume in the Building Block has a mean of 0.4171997376 and sd of 0.08.

In the DB, the mean values range from 0.00163517572098578 for 30yrs to 0.019916919926058 for the age of 30.7282832638589.

@AndreDlm Can you explain this?

**Comment by AndreDlm** [comment]
The values in the spatial structure are irrelevant; all physiological parameter values will be overwritten when importing the simulation in PK-Sim as population simulation (see [tutorial](https://ascpt.onlinelibrary.wiley.com/doi/full/10.1002/psp4.12300)).
Basically, the spatial structure BB is only used as dummy model structure that has more compartments than the PK-Sim standard model structure and the physiological values of this dummy model are only placeholders. 

Unfortunately, the pregnancy model structure cannot be combined with pregnant individuals in PK-Sim (only with populations) which may blow up computation time, but the new R toolbox allows this :)

**Comment by PavelBal** [comment]
That means that the parametrization in MoBi does not really make sense? How do you do model development, then? There is no way e.g. to run PI with populations, right?

**Comment by AndreDlm** [comment]
Model development is typically done in adults and once the model is adequate it is extrapolated to pregnancy by exchanging the spatial structure/passive transport BB (MoBi) and by parameterizing the physiology according to pregnancy stage (population import PK-Sim). That is possible. 
Model development starting specifically with a pregnant individual is not possible, though, and running a PI with a pregnancy model is neither possible (unless all parameters are correctly defined in MoBi).

However, since the pregnancy model does not involve hundreds of physiological parameters that are different from the adult ICRP model, a workaround could be to e.g. calculate the relevant parameter values in R (e.g. by using the R toolbox), write these values together with the parameter path in a table and import it as MSV in MoBi.

**Comment by AndreDlm** [comment]
@PavelBal if there are still questions, please comment/re-open
